const staffColumns = [
  { key: "checkbox", label: "Select", width: "50px" },
  { key: "profilePicture", label: "Picture", width: "100px" },
  { key: "fullName", label: "Full Name", width: "250px" },
  { key: "dateOfBirth", label: "Date of Birth", width: "120px" },
  { key: "sex", label: "Sex", width: "100px" },
  { key: "nationality", label: "Nationality", width: "140px" },
  { key: "employmentType", label: "Employment Type", width: "160px" },
  { key: "position", label: "Position", width: "250px" },
  { key: "unit", label: "Unit", width: "200px" },
  { key: "bloodType", label: "Blood Type", width: "120px" },
  { key: "dependents", label: "Dependents", width: "100px" },
  { key: "unhcrEmail", label: "UNHCR Email", width: "250px" },
  { key: "privateEmail", label: "Private Email", width: "250px" },
  { key: "mobileSyriatel", label: "Mobile (Syriatel)", width: "160px" },
  { key: "mobileMtn", label: "Mobile (MTN)", width: "160px" },
  { key: "homePhone", label: "Home Phone", width: "160px" },
  { key: "extension", label: "Extension", width: "100px" },
  { key: "radio", label: "Radio", width: "100px" },
  { key: "emergencyContact", label: "Emergency Contact", width: "200px" },
  { key: "contractType", label: "Contract Type", width: "140px" },
  { key: "contractStartDate", label: "Contract Start Date", width: "170px" },
  { key: "contractEndDate", label: "Contract End Date", width: "170px" },
  { key: "nationalIdNumber", label: "National ID Number", width: "170px" },
  { key: "passportNumber", label: "Passport Number", width: "170px" },
  { key: "passportExpiryDate", label: "Passport Expiry Date", width: "180px" },
  { key: "unlpNumber", label: "UNLP Number", width: "170px" },
  { key: "unlpExpiryDate", label: "UNLP Expiry Date", width: "170px" },
  { key: "criticalStaff", label: "Critical Staff", width: "120px" },
  { key: "warden", label: "Warden", width: "120px" },
  { key: "floorMarshal", label: "Floor Marshal", width: "140px" },
  { key: "etb", label: "ETB", width: "100px" },
  { key: "ifak", label: "IFAK", width: "100px" },
  { key: "advancedDriving", label: "Advanced Driving", width: "170px" },
  { key: "insideDs", label: "Inside DS", width: "120px" },
  { key: "outsideDs", label: "Outside DS", width: "120px" },
  { key: "address", label: "Address", width: "250px" },
  { key: "actions", label: "Actions", width: "120px" },
];

export default staffColumns;
